### ISSUE TITLE
unpubd up : fails with MongoDart Error: Authentication failed.

### ISSUE THREAD

**Issue by manukj** [bsutton/unpubd#1]
,"codeName":"ProtocolError","errmsg":"Attempt to switch database target during SASL authentication."}}}
mongo      | {"t":{"$date":"2021-12-06T06:45:40.164+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn11","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.18.0.3:35364","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
mongo      | {"t":{"$date":"2021-12-06T06:45:40.164+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn11","msg":"Connection ended","attr":{"remote":"172.18.0.3:35364","uuid":"1d428219-e08a-4f67-999a-60d3ba76a244","connectionId":11,"connectionCount":0}}
mongo      | {"t":{"$date":"2021-12-06T06:45:42.173+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:35366","uuid":"81ca4466-5b4b-4817-8bfd-fcafea863afd","connectionId":12,"connectionCount":1}}
mongo      | {"t":{"$date":"2021-12-06T06:45:42.180+00:00"},"s":"I",  "c":"ACCESS",   "id":5286202, "ctx":"conn12","msg":"Different user name was supplied to saslSupportedMechs","attr":{"error":{"code":17,"codeName":"ProtocolError","errmsg":"Attempt to switch database target during SASL authentication."}}}
mongo      | {"t":{"$date":"2021-12-06T06:45:43.912+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn12","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.18.0.3:35366","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
mongo      | {"t":{"$date":"2021-12-06T06:45:43.913+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn12","msg":"Connection ended","attr":{"remote":"172.18.0.3:35366","uuid":"81ca4466-5b4b-4817-8bfd-fcafea863afd","connectionId":12,"connectionCount":0}}
unpubd     | unpubd  version: 0.0.4
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDB ConnectionException: Could not connect to mongodb:27017
unpubd     | - SocketException: OS Error: Connection refused, errno = 111, address = mongodb, port = 35342
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
unpubd     | waiting for mongodb to start: MongoDart Error: Authentication failed.
unpubd     | connecting with mongodb://root:1WxMoSUUlRUZ7bQ@mongodb:27017/unpubd?authSource=admin
mongo      | {"t":{"$date":"2021-12-06T06:45:45.930+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:35368","uuid":"db2e13a3-b6a5-4ee3-9215-bda6b1458b8e","connectionId":13,"connectionCount":1}}
mongo      | {"t":{"$date":"2021-12-06T06:45:45.936+00:00"},"s":"I",  "c":"ACCESS",   "id":5286202, "ctx":"conn13","msg":"Different user name was supplied to saslSupportedMechs","attr":{"error":{"code":17,

**Comment by manukj** [comment]
not sure what the issue was,
I uninstalled unpub which was installed previously and installed unpubd

**Comment by bsutton** [comment]
I've been able to reproduce it here so will he have a look. I don't believe
it relates to unpub as we're are isolate in a Docker container.

**Comment by jamieastley** [comment]
This is still reproducible and shouldn't be closed, I'm running into this same issue while trying to get this up and running on my DigitalOcean droplet.
