### ISSUE TITLE
Mongo Driver

### ISSUE THREAD

**Issue by saadahmedlime** [bsutton/unpubd#5]
Whenever I try to run unpubd on a kubernates cluster It gives me that following error

`errmsg: Unsupported OP_QUERY command: count. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal, code: 352, codeName: UnsupportedOpQueryCommand}
package:shelf/src/middleware/logger.dart 32  logRequests.<fn>.<fn>.<fn>
`
Should I Manually downgrade or upgrade the mongo db database ?

**Comment by bsutton** [comment]
I'm not going to be much help here as I'm not a mongo expert.

I would try upgrading the mongo package.

As an alternate you can get a free license on https://onepub.dev which provides the same service without having to maintain your own server.

Disclaimer: I'm the founder of OnePub.
